### ISSUE TITLE
Mappings

### ISSUE THREAD

**Issue by njordhov** [crystalscript/crystalscript#7]
Congratulations on the launch!

The [data maps](https://github.com/crystalscript/crystalscript/blob/main/docs/language-reference.md#data-maps) section of the documentation uses the word _map_ for persisted key-value _mappings_. I suggest using the latter term as the word "map" can be confused with the function.

Solidity also has a similar [mapping](https://www.tutorialspoint.com/solidity/solidity_mappings.htm) type, generally used for state variables.

**Comment by crystalscript** [comment]
Thanks! I updated the docs to use "data map" more consistently. I agree that using the word 'map' could be confusing (because there is a "data map", "persistent map", "map" system call, and "map" type). I'll have to consider that more (in issue #8).
